---
title: "5110 CH2 P1"
author: "Yifan YE"
date: "10/19/2018"
output: html_document
---
## 2.0 Scatter Plot and Correlation

Pearson correlation coefficient only test for linear relationships and it can do nothing about non-linear relationship. 

```{r loading data}
# Refer to the data sets of the returns of the stocks SP500 and GE (Ch1)
# The S\&P 500 stock market index, maintained by Standard \& Poor\'s, comprises 500 large-cap American companies covering about 75% of the American equity market by capitalization

#Daily Data for S&P500 stock market index from Jan 3 2000 to July 27 2011 (Source from http://www.optiontradingtips.com/resources/historical-data/sp500.html) Variables: Date, Open, High, Low, Close, Volume Date column is of format yyyymmdd, where y = year, m = moth and d = day

spclose=read.table("sp500.txt",head=T)[,5]
geclose=read.table("geDJ.txt",head=T)[,5]
```

```{r diff and lag}
# Lag (quantmod):
# Compute a lagged version of a time series, shifting the time base back by a given number of observations
# Lag(x, k = 1)
# x: a numeric vector or series to be lagged; k: periods to lag.

# diff(base):
# Returns sitably lagged and iterated differences.
# diff(x, lag = 1)
# x: a numeric vector containing the values to be differenced.

logrcSP = diff(log(spclose), lag = 1)
logrcGE = diff(log(geclose), lag = 1)

plot(logrcSP, logrcGE)
```

```{r cor}
cor.test(logrcGE, logrcSP, method = "pearson")
cor.test(logrcGE, logrcSP, method = "spearman")
cor.test(logrcGE, logrcSP, method = "kendall")
```

## 2.1 Simple OLS 

```{r OLS 1}
# Scatter plot
plot(logrcSP, logrcGE, ylab = "log return of the daily closing price for General Electric@DowJones30", 
xlab ="log return of the daily closing price for S&P500")

# Add a least-squares fitted straight line 
abline(lm(logrcGE~logrcSP) )
```

```{r OLS 2}
# Simple linear regression model
lm(logrcGE~logrcSP)

# More information
summary(lm(logrcGE~logrcSP))
# or
# fit = lm(logrcGE~logrcSP)
# summary(fit)
```

```{r OLS 3}
fit = lm(logrcGE~logrcSP)
anova(fit)
```

```{r OLS test}
################# Hypothesis testing for beta_0 and beta_1 ############################################

# install.packages("car")
library("car")

linearHypothesis(fit, "logrcSP = 1")
linearHypothesis(fit, "(Intercept) = 0.05")

linearHypothesis(fit, diag(2),  c(0.05, 1))
```

```{r OLS C.I.}
############################################ 90% C.I.############################################
confint(fit, level = 0.9)
```

```{r no intercept}
#### Fit a simple linear regression model WITHOUT intercept term ############################################
lm(logrcGE ~ -1 + logrcSP)
summary(lm(logrcGE ~ -1 + logrcSP))
```

```{r pred}
######## Prediction ############################################
new = data.frame(logrcSP = 0.08)
predict(fit, new)

new = data.frame(logrcSP = c(0.08, -0.07))
predict(fit, new)

new = data.frame(logrcSP = 0.08)
predict(fit, new, interval = "prediction", level = 0.9)

new = data.frame(logrcSP = 0.08)
predict(fit, new, interval = "confidence", level = 0.9)
```

```{r plot}
plot(logrcSP, logrcGE)
fit = lm(logrcGE~logrcSP)
abline(fit, col = "red")

z = cbind(logrcSP, logrcGE)
z1 = data.frame(z[order(z[,1]),])

fit1 = lm(logrcGE~logrcSP, data = z1)

cl = predict(fit1, interval = "confidence", level = 0.9)[,2]
cu = predict(fit1, interval = "confidence", level = 0.9)[,3]
lines(z1$logrcSP, cl, col = "blue", lty = 3)
lines(z1$logrcSP, cu, col = "blue", lty = 3)

pl = predict(fit1, interval = "prediction", level = 0.9)[,2]
pu = predict(fit1, interval = "prediction", level = 0.9)[,3]
lines(z1$logrcSP, pl, col = "green", lty = 2)
lines(z1$logrcSP, pu, col = "green", lty = 2)

legend(x="bottomright", c("90% confidence interval", "90% prediction interval"), col = c("blue", "green"), lty = c(3, 2))
```

## Appendix: Applications in Finance

```{r interest rate application}
# Variables are:
# month, day, year
# ff (Federal funds rate)
# tb03 (3 month t-bill rate)
# cm10 (constant maturity 10-year Treasury bond rate)
# cm30 (constant maturity 30-year Treasury bond rate)
# discount
# prime
# aaa  (corporate AAA bond yield )

# The value 0 in each cell is used for missing data
# Note that there is no information of the data on the last column in the original data set 
# However, we will not use it in our analysis, so I simply use a variable k to store this data 

# R codes: Simple Linear Regression model with interest rates 
weeklyinterest = read.table("1_weeklyinterest.txt")

# column: month, day, year, ff, tb03, cm10, cm30, discount, prime, aaa, k
aaa_dif = diff(weeklyinterest[, 10],lag = 1)
cm10_dif = diff(weeklyinterest[, 6],lag = 1)

# Scatter plot 
plot(cm10_dif, aaa_dif, ylab = "Change in the corporate AAA bond yield", xlab = "Change in the 10-year Treasury rate", main = "Weekly Interest Rates")

# Simple Linear Regression model with cm10_dif 
f1 = lm(aaa_dif~cm10_dif)

# Scatter plot with a fitted line
plot(cm10_dif, aaa_dif, ylab = "Change in the corporate AAA bond yield", xlab = "Change in the 10-year Treasury rate", main = "Weekly Interest Rates")
abline(f1)


# Details about the fitted regression line with cm10_dif 
summary(f1)

# Construct 90% C.I. for each of the regression coefficients 
confint(f1, level = 0.9)

# The intercept term is INsignificant 
# Simple linear regression without intercept 
f10 = lm(aaa_dif~-1+cm10_dif)
summary(f10)
```

```{r CAPM 1}
z = read.table("2_charAB.txt", sep = "\t", head = T)
colnames(z)[2:4] = c("rm", "ra", "rb")
 
modelA = lm(ra~rm, data = z)
summary(modelA)

modelB = lm(rb~rm, data = z)
summary(modelB)
```

```{r CAPM 2}
# Refit the data for FUND B without intercept
modelB0 = lm(rb~-1+rm, data = z)
summary(modelB0)


# Now we use the fitted model to forecast the expected stock returns for Fund B next year.Suppose we expect the market return to be 10% next year and the risk free rate will be 3%.  

# Prediction of excess return (in %)
new = data.frame(rm = 7)
predict(modelB0, new, interval = "confidence", level = 0.95)
predict(modelB0, new, interval = "prediction", level = 0.95)

# Prediction of return (in %)
predict(modelB0, new, interval = "prediction", level = 0.95)[1] + 3
```

```{r CAPM 3}
z = read.table("3_capm.txt", sep = "\t")
sp_dif = diff(log(z[,3]), lag = 1)
msft_dif = diff(log(z[,2]), lag = 1)

tbillp = z[-1, 1]/(100*253)

excess_R_sp500 = sp_dif - tbillp
excess_R_msft = msft_dif - tbillp

fcapm = lm(excess_R_msft~excess_R_sp500)

# Print out the results
summary(fcapm)

##################################### 90% C.I. (optional) ###############################
# confint(fcapm, level = 0.9)

########### Fit a simple linear regression model WITHOUT intercept term #######################################
fcapm0 = lm(excess_R_msft~excess_R_sp500-1)
summary(fcapm0)

########Hypothesis testing for beta_1#############
# install.packages("car")
library("car")
linearHypothesis(fcapm0, "excess_R_sp500 = 1")  # Note that there is only ONE parameter for slope 
```
