---
title: "In-class Exercise"
author: "Yifan YE"
date: "12/14/2018"
output: html_document
---

## Assignment 1

```{r loading data 1}
geDJ = read.table("geDJ.txt", header = T) # read.table function
geDJ$date = as.Date(as.character(geDJ$date), "%Y%m%d") # D is upper case, % is before Y
head(geDJ) # head function
summary(geDJ)
colnames(geDJ)
```

```{r boxplot}
library(zoo)
close.geDJ = zoo(x = geDJ$close, order.by = geDJ$date)
ret = log(close.geDJ)-lag(log(close.geDJ), k = -1) # pay attention to the usage of k
# as.vector(ret)
# time(ret) # time series
boxplot(as.vector(ret), main = "title", xlab = "x", ylab = "y")
```

```{r descriptive statistics}
library(moments)
ret_geDJ = as.vector(ret)
n = length(ret_geDJ)
mean(ret_geDJ)
var(ret_geDJ)
sd(ret_geDJ)
skewness(ret_geDJ)*sqrt(n*(n-1))/(n-2) # adjusted
kurtosis(ret_geDJ)*(n+1)*(n-1)/((n-2)*(n-3))-(3*(n-1)*(n-1))/((n-2)*(n-3)) # adjusted
```

```{r qqplot}
qqnorm(ret_geDJ)
qqline(ret_geDJ, col = "blue", lty = 4)
```

```{r hypothesis test}
t.test(ret_geDJ, mu = 0, alternative = "two.sided")
t.test(ret_geDJ, mu = 0, conf.level = 0.95) # or other different significant level
```

```{r normality tests}
shapiro.test(ret_geDJ)
ks.test(ret_geDJ, "pnorm", mean = mean(ret_geDJ), sd = sd(ret_geDJ))
library(pgirmess)
ks.gof(ret_geDJ)
library(nortest)
ad.test(ret_geDJ)
```

```{r Wilcoxon test}
wilcox.test(ret_geDJ, mu = 0, alternative = "two.sided", exact = F, correct = T) # test for median
```

```{r two samples}
# compare S&P500 and geDJ
sp500 = read.table("sp500.txt", header = T) # read.table function
sp500$date = as.Date(as.character(sp500$date), "%Y%m%d") # D is upper case, % is before Y
colnames(sp500) = c("date", "open", "high", "low", "close", "vol")
head(sp500) # head function
close.sp500 = zoo(x = sp500$close, order.by = sp500$date)
ret_sp500 = as.vector(log(close.sp500)-lag(log(close.sp500), k = -1))
boxplot(ret_sp500, main = "title", xlab = "x", ylab = "y")
boxplot(ret_sp500, ret_geDJ, main = "title", xlab = "x", ylab = "y")
```

```{r two sample test}
# Wilcoxon test for two samples
wilcox.test(ret_sp500, ret_geDJ, mu = 0, paired = F, alternative = "two.sided", exact = F, correct = T)
# medians are equal
```

## Assignment 2

```{r loading data 2}
cw2q3 = read.table("cw2q3.txt", header = T, sep = "\t") # read.table function
head(cw2q3)
```

```{r OLS}
modelA = lm(excess_return_fund_A~market_excess_return, data = cw2q3) # with intercept
modelB = lm(excess_return_fund_B~market_excess_return, data = cw2q3) # with intercept
summary(modelA)
summary(modelB)
```

```{r no intercept}
modelBB = lm(excess_return_fund_B~market_excess_return-1, data = cw2q3) # no intercept
summary(modelBB)
```

```{r prediction 1}
new = data.frame(market_excess_return = 7)
predict(modelBB, new, interval = "confidence", level = 0.95)
predict(modelBB, new, interval = "prediction", level = 0.95)
```

```{r test}
# check if beta is equal to 1
library(car)
linearHypothesis(modelBB, "market_excess_return = 1")
```

## Assignment 3

```{r loading data 3}
cw3_q1 = read.table("cw3_q1.txt", header = T) # read.table function
head(cw3_q1)
```

```{r best subset selection}
library(leaps)
library(bestglm)
EPS = cw3_q1$EPS
sales = cw3_q1$sales
AE = cw3_q1$AE
cost = cw3_q1$cost
designx = cbind(sales, AE, cost)

leaps(designx, EPS, method = "Cp")
leaps(designx, EPS, method = "adjr2")

Xy=cbind(as.data.frame(designx), EPS)
bestglm(Xy, IC="AIC")
bestglm(Xy, IC="BIC")
```

```{r fwd and bkd selection}
fit_full = lm(EPS~sales+AE+cost, data = cw3_q1)
fitbkd = step(fit_full, direction = "backward") # we need AIC to decrease 
fitbkd

fit0 = lm(EPS~1)
fitfwd = step(fit0, direction = "forward", scope = (~sales+AE+cost)) # we need AIC to decrease 
fitfwd

fitstep = step(fit0, direction = "both", scope = (~sales+AE+cost)) # we need AIC to decrease 
fitstep 
```

```{r prediction 2}
fitfinal = lm(EPS~AE+cost, data = cw3_q1)
new = data.frame(AE = c(175, 240), cost = c(20, 25))
predict(fitfinal, new, interval = "confidence", level = 0.97)
predict(fitfinal, new, interval = "prediction", level = 0.97)
```

```{r loading data 4}
cw3_q2 = read.table("cw3_q2.txt", header = T) # read.table function
head(cw3_q2)
time_index = 1:(dim(cw3_q2)[1])
EXEUROUS = cw3_q2$EXEUROUS
plot(time_index, EXEUROUS, type = "l")
```

```{r quadratic regression}
# quadratic regression
f1 = lm(EXEUROUS~time_index+I(time_index^2))
summary(f1)

# Plot a graph of the predicted values against time_index 
pf1 = data.frame(predict(f1))[,1]

plot(time_index, EXEUROUS, type = "l")
lines(time_index, pf1, col = "red", lty = 3)
```

```{r cubic regression}
# Cubic regression
f2 = lm(EXEUROUS~time_index+I(time_index^2)+I(time_index^3))
pf2 = data.frame(predict(f2))[,1]

summary(f2)

plot(time_index, EXEUROUS, type = "l")
lines(time_index, pf1, col = "red", lty = 3)
lines(time_index, pf2, col = "blue", lty = 2)
legend(x="bottomright", c("Quadratic", "Cubic"), col = c("red", "blue"), lty = c(3, 2))
```

```{r Quadratic spline}
# Quadratic spline

x1 = time_index
x2 = time_index^2
x3 = (time_index > 167)*(time_index-167)^2
x4 = (time_index > 334)*(time_index-334)^2

# Fit data by using a cubic spline at knots 100, 210 and 390
f_quadratic = lm(EXEUROUS~x1+x2+x3+x4)

summary(f_quadratic)

# Plot a graph of the predicted values against time_index 
pf_quadratic = data.frame(predict(f_quadratic))[,1]

plot(time_index, EXEUROUS, type = "l")
lines(time_index, pf_quadratic, col = "blue", lty = 3)
```


```{r Cubic Spline}
# Cubic Spline

x1 = time_index
x2 = time_index^2
x3 = time_index^3
x4 = (time_index > 125)*(time_index-125)^3
x5 = (time_index > 251)*(time_index-251)^3
x6 = (time_index > 377)*(time_index-377)^3

# Fit data by using a cubic spline at knots 100, 210 and 390
f_cubic = lm(EXEUROUS~x1+x2+x3+x4+x5+x6)

summary(f_cubic)

# Plot a graph of the predicted values against time_index 
pf_cubic = data.frame(predict(f_cubic))[,1]

plot(time_index, EXEUROUS, type = "l")
lines(time_index, pf_cubic, col = "blue", lty = 3)
```

```{r loading data 5}
cw3_q3 = read.table("cw3_q3.txt", header = T) # read.table function
cw3_q3$carat0 = cw3_q3$carat**(1/3)
head(cw3_q3)
```

```{r multi OLS}
fitdiamond = lm(price~carat0+cutscore+clarityscore+colorscore, data = cw3_q3)
summary(fitdiamond)
```

```{r diagnostic}
# normality test
extresid = rstudent(fitdiamond) 
# externally studendized residual

# Shapiro-Wilk test
shapiro.test(extresid)

# K-S test
# library(pgirmess)
ks.gof(extresid)

# library(nortest)
# Anderson-Darling test
ad.test(extresid)
```

```{r plots}
# Externally studentized resiudal and predicted y
extresid = rstudent(fitdiamond)
pred = predict(fitdiamond)

# Externally studentized resiudal Plot
plot(pred, extresid)

# Normal plot of extresid 
qqnorm(extresid)
qqline(extresid)
```

```{r Box-Cox transform}
library(MASS)
b = boxcox(fitdiamond, lambda = seq(-2, 2, 1/100))

# Find the point from seq(-2, 2, 1/100) at which the likelihood is maximized
b$x[which.max(b$y)]

# Use lambda = 0.1 to define a B-C transformed Y
BCprice = (cw3_q3$price^0.1-1)/(0.1)
cw3_q3bc = cbind(cw3_q3, BCprice)

fitdiamondBC = lm(BCprice~carat0+cutscore+clarityscore+colorscore, data = cw3_q3bc)
summary(fitdiamondBC)

# normality test
extresidBC = rstudent(fitdiamondBC) 
# externally studendized residual

# Shapiro-Wilk test
shapiro.test(extresidBC)

# K-S test
# library(pgirmess)
ks.gof(extresidBC)

# library(nortest)
# Anderson-Darling test
ad.test(extresidBC)

# Externally studentized resiudal and predicted y
extresidBC = rstudent(fitdiamondBC)
predBC = predict(fitdiamondBC)

# Externally studentized resiudal Plot
plot(predBC, extresidBC)

# Normal plot of extresid 
qqnorm(extresidBC)
qqline(extresidBC)
```

```{r forecast}
new = data.frame(carat0 = c(0.58**(1/3),1.03**(1/3)),cutscore = c(4,3),clarityscore = c(6,4),colorscore = c(4,2))
predict(fitdiamondBC, new, interval = "confidence", level = 0.97)
predict(fitdiamondBC, new, interval = "prediction", level = 0.97)
```

## Assignment 4

```{r loading data 6}
cw4_q1 = read.table("cw4_q1.txt", header = T) # read.table function
head(cw4_q1) # every month 19 data
```

```{r ANOVA}
rate_return = cw4_q1$rate_return
month = as.factor(cw4_q1$month) # must be a factor variable !!!!!!!!!!
boxplot(rate_return~month)
# i = data.frame(rate_return, month)
# boxplot(i$rate_return~i$month)
# plot(i$compensation~i$group), Side-by-side Boxplot

# Find the p-value of testing H0 (assumption of equal population means)
aovcw4_q1 = aov(rate_return~month)
summary(aovcw4_q1)
# pay attention to the p-value

by(rate_return, month, mean)
```

```{r loading data 7}
cw4_q2 = read.table("cw4_q2.txt", header = T) # read.table function
head(cw4_q2) # two-way anova
cw4_q2$year = as.factor(cw4_q2$year) # !!!
```

```{r two-way anova}
# Produce an interaction plot
with(cw4_q2, interaction.plot(year, fund, rreturn))

# another way
summary(aov(rreturn~year*fund, data = cw4_q2))
```

```{r anova model parameters}
coef(aov(rreturn~year*fund, data = cw4_q2))
```

```{r anova separately}
# anova separately
fund1 = subset(cw4_q2, fund == "real")
fund2 = subset(cw4_q2, fund == "government")
fund3 = subset(cw4_q2, fund == "stock")

summary(aov(rreturn~year, data= fund1))
summary(aov(rreturn~year, data= fund2))
summary(aov(rreturn~year, data= fund3))
```

```{r break down}
# break down

# aov1 = aov(rreturn~fund*year, data = cw4_q2)
# TukeyHSD(aov1, conf.level = 0.98)

group = interaction(cw4_q2$fund, cw4_q2$year)
anovamulti = aov(rreturn~group, data = cw4_q2)
summary(anovamulti)
```

```{r normality test}
# normality test
resid = residuals(anovamulti)
# Shapiro-Wilk test
shapiro.test(resid)
# Kolmogorov-Smirnov test
ks.gof(resid)
# Anderson-Darling test
ad.test(resid)
```

```{r equal variances}
# equal variance test
# Levene tests
leveneTest(cw4_q2$rreturn, group, center = "mean")
leveneTest(cw4_q2$rreturn, group, center = "median")
# Warning message is given because levene tests need more than 2 data for each group
# Fligner-Killeen test
fligner.test(rreturn~group, data = cw4_q2)
```

```{r Kruskal-Wallis test}
# Normality fails 
# (2-way -> 1-way) Kruskal-Wallis test to compare medians
kruskal.test(rreturn~interaction(fund, year), data = cw4_q2)
```



